services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

  webapi:
    build:
      context: .
      dockerfile: /Binance.WebApi/Dockerfile
    depends_on:
      - mongo
    container_name: web-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__MongoDb=mongodb://username:password@mongo:27017
    ports:
      - "8080:8080"
      - "8081:8081"